name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Build and Test
        run: make

      - name: Upload coverage
        run: bash <(curl -s https://codecov.io/bash)
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Build
        run: |
          docker build \
            --label commit=$GITHUB_SHA \
            --label build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --label tag=${{ steps.build_tag_generator.outputs.BUILD_TAG }} \
            --tag ghcr.io/hyperledger/firefly-fabconnect:${{ steps.build_tag_generator.outputs.BUILD_TAG }} .
